name: Build

on:
  push:
    branches: [ "main" ]
#    pull_request:
#        branches: [ "release" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: false
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
#      - run: flutter pub cache clean
      - run: flutter pub get
      - run: flutter test
      # Linux
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux
      # web
      - run: flutter build web
      # Android
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: flutter build apk
      - run: flutter build appbundle



  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: false
      #architecture: x64
#      - run: flutter pub cache clean
      - run: flutter pub get
      - run: flutter test
      #iOS
      - run: flutter build ios --release --no-codesign
      #MacOS
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: false
#      - run: flutter pub cache clean
      - run: flutter pub get
      - run: flutter test
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows